[package]
name = "fsorg"
version = "1.0.1"
edition = "2024"
authors = ["Harkirat Singh (honey.harkirat@outlook.com)"]
description = "File organiser utility software"

[dependencies]
log = "0.4"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.11"
