name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: cargo build --release

    - name: Get version from Cargo.toml
      id: get_version
      run: |
        VERSION=$(grep '^version' Cargo.toml | head -1 | cut -d '"' -f2)
        echo "VERSION=$VERSION"
        echo "tag_name=v$VERSION" >> $GITHUB_OUTPUT

    - name: List release folder contents
      run: ls -lh target/release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.tag_name }}
        name: Release v${{ steps.get_version.outputs.tag_name }}
        files: target/release/fsorg
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
